### PR TITLE
added new emoticons from verion 8.0 of unicode

### PR DESCRIPTION
**Pull request by parthansr**
Adding 16 new emoticons introduced in version 8.0 of unicode that are missing in current emoji set.

### CODE REVIEW

**Comment by parthansr** [comment]
I have accepted the GitHub Contributor License Ageement.

**Comment by mislav** [comment]
Hey, thanks for this, and sorry for the late reply! We can't currently pull this in until we get rid of embedded images (see https://github.com/github/gemoji/pull/72). But I'll keep this open as a reminder that we need to add the new emoji at some point.

**Comment by parthansr** [comment]
No problem. I tried fixing it locally and thought I could send it upstream. Would be great if the new emojis could be included as soon as possible.

**Comment by parthansr** [comment]
Thanks @mislav. Awaiting the 3.0 release to fix all the new emoji issues.

**Pull request closed without merging**
