### PR TITLE
Unicode 10.0, Emoji 5.0 (2017)

### PR DESCRIPTION
**Pull request by Crissov**
- entries have not been sorted into the right places
- information directly taken from http://unicode.org/emoji/charts/emoji-released.html
- solves #134

### CODE REVIEW

**Comment by stefanzweifel** [comment]
Anything missing to get this PR into master?

**Comment by mislav** [comment]
@stefanzweifel Yes: because of changes in macOS, we need to first figure out #142 before we can keep updating the database with new characters, otherwise we have no way to run tests and verify that we've covered all the characters that Apple supports in the latest version.

**Comment by Crissov** [comment]
@koddsonʼs PR is indeed die this one irrelevant because it pulls the required data for `emoji.json` from Unicode / CLDR.

**Comment by mislav** [comment]
We now support Unicode 11 https://github.com/github/gemoji/pull/155. Thank you for your patience!

**Pull request closed without merging**
