### PR TITLE
Remove dependency on apple

### PR DESCRIPTION
**Pull request by koddsson**
Hey @mislav 👋 Here's a push of some of the changes I made a few weeks ago. It feels pretty hacky right now but I think the thinking here makes sense.

The thinking is mostly that `gemoji` should not track `ios_version` any more and shouldn't fetch info from a operating system but rather the data from the unicode consortium.

I'm interested in hearing what you think. I might want to break this down into multiple, more digestable chunks 😃

### CODE REVIEW

**Comment by koddsson** [comment]
To make this PR simpler, I have rebased 4f2464f and 377beba out for another PR

**Comment by koddsson** [comment]
The diff keeps shrinking! I'll hack on this more and more and see if I can get it down to 0 😄

**Comment by andrewjmeier** [comment]
@koddsson Any plans to try and push this PR through so we can get updated emoji?

**Comment by mislav** [comment]
Superseded by https://github.com/github/gemoji/pull/155

**Pull request closed without merging**
