### PR TITLE
Undefined method `image_filename=`

### PR DESCRIPTION
**Pull request by i-arindam**
The file in the commit mentions my problem.
Since I couldn't create an Issue

### CODE REVIEW

**Comment by mislav** [comment]
Hi there! That's a pretty smart workaround for the fact we don't have an issue tracker :smile: 

`image_filename` customization feature was added in ac3620cf89baca5f50ddf9cd0d759aea009086d1 which wasn't released yet. You're reading documentation on this repo, but that shows documentation for the current state of the master branch, not the version you have installed (v2.1.0).

What you should do is:

```rb
Emoji.create("jenkins_success")
```

and then create a `jenkins_success.png` image in the same directory as other custom emoji such as `shipit.png`.

**Comment by i-arindam** [comment]
Yup it worked.
fwiw, we have our images in `public/images/emoji`

Just so I understand this correct, the `image_filename` feature has not been gemmified yet ?

**Comment by mislav** [comment]
Yes, the `image_filename=` feature will be a part of the next release, but it isn't in any gem right now.

**Comment by i-arindam** [comment]
Thanks for the explanation @mislav 

Shouldn't the documentation be obscuring the `image_filename=` part until that feature is available as part of the gem, in order to avoid this confusion.

I'd be happy to raise a PR!

**Comment by mislav** [comment]
No. The documentation in this repo is always for the master branch by default, which is not guaranteed to be released yet (and it most cases it isn't with constantly evolving projects).

If you want to view documentation for your currently installed version, please browse that tag on GitHub:
https://github.com/github/gemoji/blob/v2.1.0/README.md#adding-new-emoji

**Pull request closed without merging**
