### PR TITLE
Replace emoji with opensource versions

### PR DESCRIPTION
**Pull request by paradox460**
As outlined in #61, the images from AppleColorEmoji are :copyright: by Apple, and as such, their distribution is a violation of copyright law.

There *is*, however, a complete opensource emoji font, that actually includes 27 more emoji than the Apple emoji, within the unicode ranges of `1f1e6...20e3`.

That font is [Noto](https://www.google.com/get/noto/), which is developed by Google. It is also used in several of Google's products, such as Google+, Gmail, Hangouts, and Android. Yes, its the android Emoji font set.

Interestingly enough, the color emoji from Noto are available as both PNG and as SVG, as can be seen [here](https://code.google.com/p/noto/source/browse/color_emoji). The SVG option is of particular interest, because it may allow for the replacement of images with inline SVG or at least [SVG symbols](http://css-tricks.com/svg-symbol-good-choice-icons/).

Noto is licensed under Apache, which is compatible with the MIT license Gemoji uses.

----

For this PR, I just converted all the SVGs from Noto to PNGs at the appropriate size, renamed them, and overwrote the existing icons. I then deleted the surplus icons, wich have no equivalent in Apple color emoji.

Unfortunately, by doing it this way, I managed to break almost all the tests :disappointed:. This means that this PR probably shouldn't be merged.

If there is interest in fixing gemoji to be fully opensource, a good solution would probably be:

1. Replace the code that converts AppleColorEmoji to PNGs with a code that converts Noto SVGs to PNGs.
  + Imagemagick, when compiled with the proper SVG libraries, can do this out of the box, fairly quickly
2. Rewrite the tests to make use of the new behavior.
  + Possibly use the latest Unicode Emoji reference, rather than one maintained by Apple

Switching, wholesale, to SVG, is a little more complicated, but is also an option.

Thoughts?

### CODE REVIEW

**Comment by Veronica36** [comment]
I need a deleted video. ..home made undeleted

**Comment by obskyr** [comment]
Whoops. That "several years down the road" turned into months, I guess...

**Comment by mislav** [comment]
Just to let everyone know that I have plans to change this library sometime in May (when I return from vacation) to allow picking between different emoji sets. Support for Fitzpatrick modifiers for skin color may also be coming as a 2nd step. Note that none of the opensource sets currently support skin color modifiers.

The goal is that gemoji stops shipping with PNG images, and to offer scripts to download/extract an image set in a size and to a directory of your choice.

**Comment by mislav** [comment]
Since we won't accept this PR, because it adds images, this feature is now tracked as #72. Thanks for the discussion!

**Pull request closed without merging**
