### PR TITLE
Offer a choice between different emoji sets

### PR DESCRIPTION
**Pull request by mislav**
:construction: :construction:

The next major version of gemoji will focus on removing all embedded images and ship only with extraction scripts that will handle:
- Apple Color Emoji
- Emoji One
- Twemoji
- Google Hangouts/Android emoji

The extraction scripts will take desired image dimensions and destination directory and pull down an entire emoji set, optimized for file size, and extract into the destination.

/cc @paradox460 @djfpaagman

### CODE REVIEW

**Comment by obskyr** [comment]
Just popping in to offer the info that the Google / Android emoji are part of a font called Noto, developed by Google. SVGs and 128x128 PNGs are available in [the Noto Google Code repository](https://code.google.com/p/noto/).

**Comment by javan** [comment]
:shipit: :grin:

**Comment by paradox460** [comment]
Noto is still hosted on Google code, via svn

Might be advantageous to mirror it to git...

**Comment by djfpaagman** [comment]
sweet! Happy to help if you want :grin:

**Comment by mislav** [comment]
Just a heads-up to everyone that I'm back from 2-week vacation and will be proceeding with this soon. I might enlist help during the process. My plan of action:

1. Download all open source sets.
2. Normalize their filenames.
3. Compare the sets for whether they implement the full emoji range that Apple implements.
4. Optimize PNGs through ImageOptim and ImageAlpha.
5. Package the tarballs and upload to somewhere in this repo (possibly Releases section).
6. Write script that asks you for a set name and PNG dimensions and fetches the appropriate tarball.

**Comment by webmaven** [comment]
Which emoji set is the one used by GitHub?

**Comment by obskyr** [comment]
@webmaven Apple's.

**Comment by webmaven** [comment]
@obskyr So, will the latest ones [added by Apple](http://emojipedia.org/new-ios-9-1/) be included as well?

**Comment by mislav** [comment]
Sorry I haven't had time to work on this since the last update. Yes, latest emoji by Apple will be supported, although their images will not be included in the distribution.

**Comment by oldmud0** [comment]
I am looking forward to this update.

**Comment by nicolasmlv** [comment]
If you want to build a script that auto-extract from [emoijone](https://github.com/Ranks/emojione), i used this : https://gist.github.com/nicolasmlv/2d79473bd93e1ec56f34

**Comment by mislav** [comment]
I've just pushed an update to master that deletes all the embedded Apple emoji images from source code. If a user wants to generate those images for their application, they need to be on macOS Sierra (or newer) and run the new exectuable that extracts the images:

```
gemoji extract public/images/emoji
```

Our internal emoji list has been updated to encompass all the newest emoji up to and including iOS 10.0 and macOS Sierra.

I haven't made progress yet on supporting other emoji sets such as Emoji One, but that's planned in the next release.

**Comment by Crissov** [comment]
You could reuse https://github.com/iamcal/emoji-data/ for this.

**Comment by mislav** [comment]
This library is now a source of information about Unicode emoji only (no custom emoji) and doesn't offer integration with any known emoji illustration set, not even Apple's.

https://github.com/github/gemoji/releases/tag/v4.0.0.pre0
https://github.com/github/gemoji/releases/tag/v4.0.0.rc1

I will likely not get to implement an extractor for other emoji sets, so this is left as an exercise to whoever uses this library.

**Pull request closed without merging**
