### PR TITLE
Import Emoji 14.0 characters

### PR DESCRIPTION
**Pull request by kardeslik**
https://emojipedia.org/emoji-14.0/

The iOS version where these emojis are added is 15.4 ([source](https://emojipedia.org/apple/)).

This solves #237

### CODE REVIEW

**Comment by novacrazy** [comment]
May as well update this to Unicode 15 sometime.

**Review by Genericreqd — APPROVED** [review]

**Review by mislav — APPROVED** [review]
Thank you! Looks great

**Comment by novacrazy** [comment]
Out of curiosity, what is the source of these? Tags, aliases, etc.

**Comment by mislav** [comment]
We mostly generate initial aliases from the character descriptions in the Unicode spec. Sometimes we just straight-up invent aliases (for the most common emoji). Tags we add at our own discretion to aid searching in emoji pickers that use this library.

**Pull request merged**
