### PR TITLE
High-Resolution Doomguy

### PR DESCRIPTION
**Pull request by Crissov**
Replacing the classic Doomguy images by [high resolution versions from a Doom (rather ZDoom) mod, by “Reinchard”](https://www.dropbox.com/s/8q4qhh7fdizembx/R_Hud_Stuff_ZDoom_v1.zip?dl=0), real name: Ryszard Stanoszek.

[3D Arch Design on Behance](https://www.behance.net/gallery/47659943/Doomguy)

[Twitter@Reinchard777](https://twitter.com/Reinchard777/status/615208099792703489)

### CODE REVIEW

**Comment by Crissov** [comment]
What's holding this back? The license issue should be less of a problem than with Apple or ID art.

**Comment by Crissov** [comment]
The Behance page seems to tag the graphics as CC BY-NC-ND for what it's worth.

**Comment by mislav** [comment]
Our doomguy is in gemoji for historical purposes. I don't know who put it there originally, but I'm guessing it was meant as a ligh-hearted homage to the original Doom series.

The high-resolution images are not a good fit for gemoji. First of all, we don't need images larger than 64x64 px. Second, the updated images are too detailed and thus too graphic, while the original images, especially because they are "low-res" (pixellated), serve much nicer as a callback to original Doom.

We appreciate the suggestion, though!

**Comment by Crissov** [comment]
I thought so, but the pixelated ones also feel out of place and I stumbled over the high-resolution Doom guy independently.

**Pull request closed without merging**
