### PR TITLE
Enable Dependabot

### PR DESCRIPTION
**Pull request by zkoppert**
Dependabot could be enabled for this repository. Please enable it by merging this pull request so that we can keep our dependencies up to date and secure.

### CODE REVIEW

**Review by Kurnianazara10 — COMMENTED** [review]
icon

**Review by Pangstar41 — APPROVED** [review]

**Comment by HeriSaputra123** [comment]
[Uploading GITHUB-202410-GitHubDataProtectionAgreement.pdf…]()

**Comment by zwj66329** [comment]
gouge

**Comment by zwj66329** [comment]
8

**Pull request merged**
