### PR TITLE
Add support for latest emoji in Unicode standard

### PR DESCRIPTION
**Pull request by rrshaban**
Native support is still lagging behind, but the inclusion of all of the emoji specified in [the latest Unicode standard](http://www.unicode.org/Public/emoji/1.0/emoji-data.txt) means that gemoji will be ahead of the curve when support arrives. This could also be the beginning of adoption for these emoji. 

Not sure if this is significant? :taco: :burrito: :popcorn: :prosper: etc. are all included below, as well as outlining support for all emoji flags. 

It currently doesn't pass the "images on disk correlate 1-1 with emojis" test because, naturally, these pngs don't exist yet for most of the emoji. This is an open task; I'm not sure how to proceed with that.

### CODE REVIEW

**Comment by mislav** [comment]
Sorry, but we can't accept new emoji if the current emoji sets (Apple first and foremost) don't have images for them. Unless you can find open source images for these emoji?

**Comment by rrshaban** [comment]
@mislav it seems like [EmojiOne](https://github.com/Ranks/emojione/tree/master/assets/png) could be an open-source option for the flags, at least (not all of the emoji have a variant there, either, :taco: being a notable example). So any forward movement depends on Apple?

**Comment by mislav** [comment]
Yeah, Apple Color Emoji is our baseline, but we're going to support other sets as well. However, this library will only support emoji characters that most of the sets have implemented as image. Right now Apple Color Emoji is the leader in being the set with most images, and other sets are walking in its footsteps. I'm not aware of significant efforts of open source sets to implement standard emoji that isn't already supported by Apple.

**Comment by mislav** [comment]
Closing in favor of #72

**Pull request closed without merging**
