### PR TITLE
Add skin tones support

### PR DESCRIPTION
**Pull request by mislav**
This adds:
- `Emoji::Character#skin_tones?` - inspect support for Fitzpatrick skin tone modifiers (1F3FB-1F3FF).
- `Emoji::Character#raw_skin_tone_variants` - generate all skin tone variants for an emoji.
- `Emoji.find_by_unicode` now recognizes unicode sequences with a skin tone modifier.

### CODE REVIEW

**Comment by charvp** [comment]
Any reason this isn't merged?

**Comment by mchan2jjang** [comment]
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiittttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt

**Comment by mchan2jjang** [comment]
,

**Review by flasha89 — APPROVED** [review]

**Review by 145195 — APPROVED** [review]

**Comment by mblackritter** [comment]
Seems like someone don't want this feature and intentionally limits the use of this package - I assume there's some "woke" leftist ideologist snowflakeness behind this decision! 🙀

Missed the skin-tones in `/db/emoji.json`, but yeah, an indicator on each would already do, then we can generate the variants ourselves, true! 😻

**Comment by mislav** [comment]
@chvp Sorry for my late reply. This reason this wasn't merged is because `emoji.skin_tones?` on its own wasn't very useful to ship. Your application would be able to detect if an emoji supported skin tones, but not much more.

I've now added support for skin tones to `Emoji.find_by_unicode` and the ability to list each skin tone variant for an emoji: `Emoji::Character#raw_skin_tone_variants`.

**Pull request merged**
