### PR TITLE
ZWJ sequences for custom images

### PR DESCRIPTION
**Pull request by Crissov**
implements #120
I'd welcome suggestions for alternative sequences

### CODE REVIEW

**Comment by Crissov** [comment]
This fails because the code currently expects all custom emojis to have no Unicode representation (`raw`, `unicode_aliases.first`), which is exactly what I'm trying to change here, but I don't speak Ruby and my trial-and-error approach documented above wasn't successful. (This pull request should be squash-merged if it's fixed.)

**Comment by mislav** [comment]
Hi thanks for the suggestion! Why would it be useful to have ZJW sequences for custom emoji? How are people expected to input such sequences?

**Comment by Crissov** [comment]
They would be copied in plain-text environments, i.e. while the Octocat cannot​ be shown, 🐱🐙 can and users would be able to guess or learn what is missing there.

**Comment by ahmeddiini** [comment]
hg

**Pull request closed without merging**
